services:
  mysql:
    image: mysql:latest
    container_name: mysql_vert_anw
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: VA_APP
    ports:
      - "3312:3306"


  redict:
    image: registry.redict.io/redict:alpine
    # using redict instead of redis
    container_name: redict_vert_anw
    ports:
      - "6379:6379"